image: markoshust/magento-php:whatiswrongwithyou

pipelines:
  default:
    - step:
        name: Integration Tests
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - ./bin/pipelines-test.sh
        services:
          - db
          - app
definitions:
  services:
    db:
      image: integernet/mysql_ci:5.6
      environment:
        MYSQL_DATABASE: magento
        MYSQL_ROOT_PASSWORD: magento
    app:
      image: markoshust/magento-nginx:1.13
